/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Control.*;
import dibujos.lienzoTablero;
import dibujos.lienzoCanias;
import POJOS.*;
import dibujos.LienzoFichas;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo 4
 */ 
public class FramePartida extends javax.swing.JFrame {
    private Partida partida;   
    private controlPartida controlPartida;
    private lienzoTablero lt;
    private lienzoCanias lc;
    private LienzoFichas lf;
    /**
     * Creates new form FramePartida
     * @param partida
     */
    public FramePartida(Partida partida) {        
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        this.partida = partida;
        this.controlPartida = new controlPartida(this.partida);
        this.cargarPaneles();
        initComponents();
        this.jLCodigo.setText(this.partida.getCodigo());
        this.cargarJugador();
        this.setBounds(0, 0, 1300, 700);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLNomJug1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfFichas1 = new javax.swing.JTextField();
        tfPuntos1 = new javax.swing.JTextField();
        tfFondos1 = new javax.swing.JTextField();
        btTirarCañas1 = new javax.swing.JButton();
        btSalir1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        btnTirar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLNomJug1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNomJug1.setText("Nombre");

        jLabel1.setText("Fichas");

        jLabel2.setText("Puntos ");

        jLabel3.setText("Fondos");

        tfFichas1.setBackground(new java.awt.Color(240, 240, 240));
        tfFichas1.setEnabled(false);
        tfFichas1.setOpaque(false);

        tfPuntos1.setEnabled(false);

        tfFondos1.setEnabled(false);

        btTirarCañas1.setText("Tirar Cañas");
        btTirarCañas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTirarCañas1ActionPerformed(evt);
            }
        });

        btSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete.png"))); // NOI18N
        btSalir1.setText("Salir");
        btSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfFichas1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPuntos1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfFondos1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLNomJug1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btTirarCañas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNomJug1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfFichas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPuntos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFondos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btTirarCañas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalir1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Código de partida:");

        jLCodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLCodigo.setText("jLabel5");

        btnTirar2.setText("Tirar cañas");
        btnTirar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTirar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTirar2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(477, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLCodigo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTirar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLCodigo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir1ActionPerformed
        FrameInicial panel = new FrameInicial();
        panel.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btSalir1ActionPerformed

    private void btTirarCañas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTirarCañas1ActionPerformed
        this.realizarTiroJ1();
    }//GEN-LAST:event_btTirarCañas1ActionPerformed

    private void btnTirar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTirar2ActionPerformed
        this.realizarTiroJ2();
    }//GEN-LAST:event_btnTirar2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalir1;
    private javax.swing.JButton btTirarCañas1;
    private javax.swing.JButton btnTirar2;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLNomJug1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfFichas1;
    private javax.swing.JTextField tfFondos1;
    private javax.swing.JTextField tfPuntos1;
    // End of variables declaration//GEN-END:variables
    
    private void realizarTiroJ1(){
    if(this.controlPartida.getTurno() == 1)
    {
        int tiro = this.partida.getAnfitrion().getCañas().tirarCania();    
        this.lc.setTirada(tiro);
        this.lc.pintarTiro();
        Ficha f = this.partida.getAnfitrion().getFichas().get(0);
        f = this.controlPartida.actualizarFicha(tiro, f);
        this.partida.addFicha(f);    
        ArrayList<Ficha> fichas = this.partida.getAnfitrion().getFichas();
        fichas.set(0, f);
        this.partida.getAnfitrion().setFichas(fichas);
        this.lf.setFichas(this.partida.getFichasJuego());
        this.lf.actualizar();
        this.controlPartida.cambiarTurno();
    }
    else{
        JOptionPane.showMessageDialog(this, "Es turno del jugador: " + this.controlPartida.getTurno(),
        "Error", JOptionPane.INFORMATION_MESSAGE);
        
    }
    }
    
    private void realizarTiroJ2(){
    if(this.controlPartida.getTurno() == 2)
    {
        int tiro = this.partida.getAnfitrion().getCañas().tirarCania();
        this.lc.setTirada(tiro);
        this.lc.pintarTiro();
        Ficha f = this.partida.getAnfitrion().getFichas().get(1);
        f.setColor("green");
        f = this.controlPartida.actualizarFicha(tiro, f);
        this.partida.addFicha(f);
        ArrayList<Ficha> fichas = this.partida.getAnfitrion().getFichas();
        fichas.set(1, f);
        this.partida.getAnfitrion().setFichas(fichas);
        this.lf.setFichas(this.partida.getFichasJuego());
        this.lf.actualizar();
        this.controlPartida.cambiarTurno();
    }
    else{
        JOptionPane.showMessageDialog(this, "Es turno del jugador: " + this.controlPartida.getTurno(),
                "Error", JOptionPane.INFORMATION_MESSAGE);
    }
    }    
/**
 * Método estatico encargado de cargar los multiples paneles que se utilizarán
 * para la graficación de los componentes.
 */
    private void cargarPaneles(){
        this.lc = new lienzoCanias();
        this.lt = new lienzoTablero(this.partida.getTablero());
        this.lf = new LienzoFichas(this.partida.getFichasJuego());
        lc.setBounds(0, 10, 800,800);
        lt.setBounds(200, -50, 800, 800); 
        lf.setBounds(200, -50, 800, 800);        
        lc.setOpaque(false);
        lt.setOpaque(false);
        lf.setOpaque(false);
        JLayeredPane capas = new JLayeredPane();
        capas.setBounds(0, 0, 1300, 800);
        capas.add(lt,3);
        capas.add(lc,2);
        capas.add(lf,1);
        this.getContentPane().add(capas);        
    }

    private void cargarJugador(){
        this.jLNomJug1.setText(this.partida.getAnfitrion().getNombre());
        this.tfFondos1.setText(this.partida.getAnfitrion().getFondos()+"");
        this.tfPuntos1.setText(this.partida.getAnfitrion().getPuntos()+"");
        this.tfFichas1.setText(this.partida.getAnfitrion().getFichas().size()+"");
    }       
}
