/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Equipo 4
 */
public class FrameInicial extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form FrameInicial
     */
    public FrameInicial() {        
        initComponents();
        this.setContentPane(fondo);
        this.setLocationRelativeTo(this);
        this.btCrearP.setEnabled(true);
        this.btBuscarP.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tfNickname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCodigoP = new javax.swing.JTextField();
        btBuscarP = new javax.swing.JButton();
        btCrearP = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla Principal");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botones6(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botones5(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botones9(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botones7(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(82, 67, 47));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfNickname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNicknameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNicknameKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quetzalcoatl.png"))); // NOI18N
        jLabel1.setText("Nickname");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contrasena (1).png"))); // NOI18N
        jLabel2.setText("Codigo partida");

        tfCodigoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodigoPKeyPressed(evt);
            }
        });

        btBuscarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btBuscarP.setText("Buscar partida");
        btBuscarP.setEnabled(false);
        btBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPActionPerformed(evt);
            }
        });

        btCrearP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/engranajes-de-configuracion.png"))); // NOI18N
        btCrearP.setText("Crear partida");
        btCrearP.setEnabled(false);
        btCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btBuscarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btCrearP)
                .addGap(51, 51, 51))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscarP)
                    .addComponent(btCrearP))
                .addGap(18, 18, 18))
        );

        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete.png"))); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
//        FrameMenu salir = new FrameMenu();
//        this.setVisible(false);
//        salir.setVisible(true);
    }//GEN-LAST:event_btSalirActionPerformed

    private void botones5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botones5
    }//GEN-LAST:event_botones5

    private void botones6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botones6
    }//GEN-LAST:event_botones6

    private void botones7(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botones7
    }//GEN-LAST:event_botones7

    private void botones9(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botones9
    }//GEN-LAST:event_botones9

    private void btCrearPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearPActionPerformed
        // TODO add your handling code here:
        FrameCrearPartida salir = new FrameCrearPartida();
        this.setVisible(false);
        salir.setVisible(true);
    }//GEN-LAST:event_btCrearPActionPerformed

    private void btBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPActionPerformed
        FramePartida salir = new FramePartida();
        this.setVisible(false);
        salir.setVisible(true);
    }//GEN-LAST:event_btBuscarPActionPerformed

    private void tfNicknameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNicknameKeyTyped
        char k = evt.getKeyChar();
        if(k < 'a' || k > 'z')
        {
            evt.consume();            
        }
    }//GEN-LAST:event_tfNicknameKeyTyped

    private void tfNicknameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNicknameKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER && this.compararCampos() == 1)
        {            
            this.btCrearP.setEnabled(false);
        }
        else if(evt.getKeyCode() == evt.VK_ENTER && this.compararCampos() == 2)
        {
            this.btBuscarP.setEnabled(false);
            this.btCrearP.setEnabled(false);
        }
    }//GEN-LAST:event_tfNicknameKeyPressed

    private void tfCodigoPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoPKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER && this.compararCampos() == 1)
        {            
            this.btCrearP.setEnabled(false);
        }
        else if(evt.getKeyCode() == evt.VK_ENTER && this.compararCampos() == 2)
        {
            this.btBuscarP.setEnabled(false);
            this.btCrearP.setEnabled(false);
        }
    }//GEN-LAST:event_tfCodigoPKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicial().setVisible(true);
            }
        });
    }
    
/*Aquí empiezan los métodos que utilizará este frame*/
    
    public int compararCampos(){
    if(this.tfCodigoP.getText().isEmpty() == true && this.tfNickname.getText().isEmpty() == false)
        {            
            return 1;
        }    
    else if(this.tfNickname.getText().isEmpty() == false && this.tfCodigoP.getText().isEmpty() == false)
        {
            return 2;
        }
    else
        {
            return -1;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarP;
    private javax.swing.JButton btCrearP;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfCodigoP;
    private javax.swing.JTextField tfNickname;
    // End of variables declaration//GEN-END:variables

/*Metodo que se encarga de pintar las lineas del fondo.*/
    class FondoPanel extends JPanel {

        private Image imagen;

        public void paint(Graphics g) 
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/Aztecas4.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
